<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>BlazorHero.CleanArchitecture.Client.Infrastructure</RootNamespace>
    <AssemblyName>BlazorHero.CleanArchitecture.Client.Infrastructure</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Blazored.LocalStorage" />
    <PackageReference Include="Toolbelt.Blazor.HttpClientInterceptor" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
</Project>