<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>BlazorHero.CleanArchitecture.Application</RootNamespace>
    <AssemblyName>BlazorHero.CleanArchitecture.Application</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="LazyCache" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" />
    <PackageReference Include="System.Linq.Dynamic.Core" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\Features\Brands\Commands\AddEdit\AddEditBrandCommandHandler.ar.resx">
      <Generator>
      </Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Features\Brands\Commands\Delete\DeleteBrandCommandHandler.ar.resx">
      <Generator>
      </Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>